### ISSUE TITLE
Not working with 5.7?

### ISSUE THREAD

**Issue by danmatthews** [spatie/laravel-littlegatekeeper#11]
Sorry for the vague title! 

Without an explanation of how it's 'supposed' to work on the README, i was unsure, but currently, all it does is redirect you to the login page, i get that this is intended behavior, but not if you input the username and password set in config.

Is there supposed to be a prompt that appears before redirecting you, or are you supposed to be able to use the username and password set in `config` to log in using the login screen?

Looking at the code i wasn't able to make sense of it either.

Thanks,
Dan.

**Comment by atymic** [comment]
You need to create a controller to handle the login, then the middleware will allow you to pass.

Example:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LoginController extends Controller
{
    public function login(Request $request)
    {
        $auth = resolve('littlegatekeeper');

        $loginSuccess = $auth->attempt($request->only([
            'username',
            'password'
        ]));

        if (!$loginSuccess) {
            return response('Failed to login', 403);
        }
    }
}
```
