### ISSUE TITLE
Upgrading from 1.1.1 to 1.1.3 issue

### ISSUE THREAD

**Issue by Aktarus006** [spatie/laravel-littlegatekeeper#18]
Hello, 

I'm trying to implement your package to create a restricted area protected by a password where you can find some documents.

I updated recently from 1.1.1 to 1.1.3 and got this error message:

![image](https://user-images.githubusercontent.com/20419262/115250693-1badb780-a12a-11eb-8723-39e98fd74c78.png)

Do you know how to solve this issue?

Thanks for your help.

**Comment by MalikinSergey** [comment]
It's an effict from commit 
https://github.com/spatie/laravel-littlegatekeeper/commit/7e7a129e71aa049f69f55716e264b2cf7b23b41e

First parameter of Container::instance method must be object of class, not closure.
Instead of Container::instance method, here can be used Container::singleton.

**Comment by MalikinSergey** [comment]
> Hello,
> 
> I'm trying to implement your package to create a restricted area protected by a password where you can find some documents.
> 
> I updated recently from 1.1.1 to 1.1.3 and got this error message:
> 
> ![image](https://user-images.githubusercontent.com/20419262/115250693-1badb780-a12a-11eb-8723-39e98fd74c78.png)
> 
> Do you know how to solve this issue?
> 
> Thanks for your help.

You only need to lock this package to version 1.1.1 in your composer.json, like:

```
"spatie/laravel-littlegatekeeper": "1.1.1",

**Comment by Aktarus006** [comment]
Thank you for your answer and sorry for my late reply
